export const programs = [
  { src: '/programs/movie1.png', alt: 'Movie 1', slug: 'movie1', description: 'An enthralling cinematic experience.', youtubeId: 'dQw4w9WgXcQ' },
  { src: '/programs/movie2.png', alt: 'Movie 2', slug: 'movie2', description: 'A tale of adventure and discovery.', youtubeId: 'Yce_3wt2n0o' },
  { src: '/programs/movie3.png', alt: 'Movie 3', slug: 'movie3', description: 'A heartwarming story of friendship.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/movie4.png', alt: 'Movie 4', slug: 'movie4', description: 'A gripping thriller that will keep you on the edge of your seat.', youtubeId: '3JZ_D3_ELwOQ' },
  { src: '/programs/movie5.png', alt: 'Movie 5', slug: 'movie5', description: 'A hilarious comedy for the whole family.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/movie6.png', alt: 'Movie 6', slug: 'movie6', description: 'A classic tale of love and loss.', youtubeId: 'dQw4w9WgXcQ' },
  { src: '/programs/music.png', alt: 'Music', slug: 'music', description: 'A collection of the latest and greatest hits.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/sports1.png', alt: 'Sports 1', slug: 'sports1', description: 'Action-packed sports coverage.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/amooti.jpg', alt: 'Amooti', slug: 'amooti', description: 'A hilarious stand-up special from Amooti.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/afrobeat1.jpg', alt: 'Afrobeat 1', slug: 'afrobeat1', description: 'The best of Afrobeat music.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/pop.jpg', alt: 'Pop', slug: 'pop', description: 'The ultimate pop music collection.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/dr.hillary.jpg', alt: 'Dr Hillary', slug: 'dr-hillary', description: 'An inspiring documentary about Dr. Hillary.', youtubeId: 'Yce_3wt2n0o' },
  { src: '/programs/kansiime.jpg', alt: 'Kansiime', slug: 'kansiime', description: 'Laugh out loud with Kansiime\'s comedy special.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/sportmovie8.jpg', alt: 'Sport Movie 8', slug: 'sportmovie8', description: 'An underdog story in the world of sports.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/musicmovie.jpg', alt: 'Music Movie', slug: 'musicmovie', description: 'A musical journey like no other.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/fun factory.jpg', alt: 'Fun Factory', slug: 'fun-factory', description: 'A variety show with comedy, music, and more.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/basketmouth.jpg', alt: 'Basketmouth', slug: 'basketmouth', description: 'A side-splitting comedy special from Basketmouth.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/sportmovie1.jpg', alt: 'Sport Movie 1', slug: 'sportmovie1', description: 'A story of triumph against all odds.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/pablo.jpg', alt: 'Pablo', slug: 'pablo', description: 'An unforgettable stand-up performance by Pablo.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/trap.jpg', alt: 'Trap', slug: 'trap', description: 'The hottest trap music playlist.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/rnb.jpg', alt: 'RnB', slug: 'rnb', description: 'Smooth and soulful RnB tracks.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/sportmovie6.jpg', alt: 'Sport Movie 6', slug: 'sportmovie6', description: 'A story of teamwork and perseverance.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/musicmovie.jpg', alt: 'Music Movie', slug: 'musicmovie-2', description: 'A musical masterpiece.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/rnb2.jpg', alt: 'RnB 2', slug: 'rnb2', description: 'More of the best RnB music.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/trevor noah.jpg', alt: 'Trevor Noah', slug: 'trevor-noah', description: 'A thought-provoking and hilarious special from Trevor Noah.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/event8.jpg', alt: 'Event 8', slug: 'event8', description: 'Highlights from the most exciting event of the year.', youtubeId: 'Yce_3wt2n0o' },
  { src: '/programs/sportdoc1.jpg', alt: 'Sport Doc 1', slug: 'sportdoc1', description: 'An in-depth look at the world of sports.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/volley.jpg', alt: 'Volley', slug: 'volley', description: 'Thrilling volleyball action.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/upl.png', alt: 'UPL', slug: 'upl', description: 'The best of the Ugandan Premier League.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/movie6.png', alt: 'Movie 6', slug: 'movie6-2', description: 'A cinematic classic revisited.', youtubeId: 'dQw4w9WgXcQ' },
  { src: '/programs/musicdoc1.jpg', alt: 'Music Doc 1', slug: 'musicdoc1', description: 'A documentary that explores the life of a music legend.', youtubeId: '3JZ_D3ELwOQ' },
  { src: '/programs/europa league.png', alt: 'Europa League', slug: 'europa-league', description: 'The best of the Europa League.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/comedymovie3.jpg', alt: 'Comedy Movie 3', slug: 'comedymovie3', description: 'A laugh-a-minute comedy.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/champions league.jpg', alt: 'Champions League', slug: 'champions-league', description: 'The pinnacle of club football.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/comedy store.jpg', alt: 'Comedy Store', slug: 'comedy-store', description: 'The best of stand-up comedy.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/epl.jpg', alt: 'EPL', slug: 'epl', description: 'The most exciting football league in the world.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/katt williams.jpg', alt: 'Katt Williams', slug: 'katt-williams', description: 'A legendary performance by Katt Williams.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/fa.png', alt: 'FA', slug: 'fa', description: 'The oldest football competition in the world.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/event5.jpg', alt: 'Event 5', slug: 'event5', description: 'An event you won\'t want to miss.', youtubeId: 'Yce_3wt2n0o' },
  { src: '/programs/fuba.jpg', alt: 'Fuba', slug: 'fuba', description: 'The best of Ugandan basketball.', youtubeId: '_uM5kF8_evs' },
  { src: "/programs/wildn'out.jpg", alt: "Wild'n Out", slug: 'wildn-out', description: 'The wildest comedy show on television.', youtubeId: 'U-mC9Fk9_aI' },
  { src: '/programs/sportdoc3.jpg', alt: 'Sport Doc 3', slug: 'sportdoc3', description: 'A deep dive into the world of sports.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/event4.jpg', alt: 'Event 4', slug: 'event4', description: 'An unforgettable event experience.', youtubeId: 'Yce_3wt2n0o' },
  { src: '/programs/serie a.jpg', alt: 'Serie A', slug: 'serie-a', description: 'The best of Italian football.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/event1.jpg', alt: 'Event 1', slug: 'event1', description: 'The event that started it all.', youtubeId: 'Yce_3wt2n0o' },
  { src: '/programs/sportmovie3.jpg', alt: 'Sport Movie 3', slug: 'sportmovie3', description: 'A story of determination and grit.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/boxing ug.jpg', alt: 'Boxing UG', slug: 'boxing-ug', description: 'The best of Ugandan boxing.', youtubeId: '_uM5kF8_evs' },
  { src: '/programs/event1.jpg', alt: 'Event 1', slug: 'event1-2', description: 'The return of a legendary event.', youtubeId: 'Yce_3wt2n0o' },
];